/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackHome: typeof import('./../components/BackHome.vue')['default']
    CustomLoading: typeof import('./../components/CustomLoading.vue')['default']
    Default: typeof import('./../layouts/default.vue')['default']
    LanguageSwitcher: typeof import('./../components/LanguageSwitcher.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
