/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Permission: typeof import('./../components/common/RouterLink/Permission.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterLinkPermission: typeof import('./../components/common/RouterLink/Permission.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
