/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/(auth)/(permission)/(admin)/(finance)/finance': RouteRecordInfo<
      '/(auth)/(permission)/(admin)/(finance)/finance',
      '/finance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(auth)/(permission)/(admin)/(hr_technical)/hr-technical': RouteRecordInfo<
      '/(auth)/(permission)/(admin)/(hr_technical)/hr-technical',
      '/hr-technical',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(auth)/(permission)/(admin)/(hr)/hr': RouteRecordInfo<
      '/(auth)/(permission)/(admin)/(hr)/hr',
      '/hr',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(auth)/(permission)/(admin)/(technical)/technical': RouteRecordInfo<
      '/(auth)/(permission)/(admin)/(technical)/technical',
      '/technical',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(auth)/(permission)/(admin)/admin': RouteRecordInfo<
      '/(auth)/(permission)/(admin)/admin',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(auth)/(permission)/settings': RouteRecordInfo<
      '/(auth)/(permission)/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | '/(auth)/(permission)/settings/'
      | '/(auth)/(permission)/settings/advance'
      | '/(auth)/(permission)/settings/advance/'
      | '/(auth)/(permission)/settings/advance/base'
      | '/(auth)/(permission)/settings/base'
    >,
    '/(auth)/(permission)/settings/': RouteRecordInfo<
      '/(auth)/(permission)/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(auth)/(permission)/settings/advance': RouteRecordInfo<
      '/(auth)/(permission)/settings/advance',
      '/settings/advance',
      Record<never, never>,
      Record<never, never>,
      | '/(auth)/(permission)/settings/advance/'
      | '/(auth)/(permission)/settings/advance/base'
    >,
    '/(auth)/(permission)/settings/advance/': RouteRecordInfo<
      '/(auth)/(permission)/settings/advance/',
      '/settings/advance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(auth)/(permission)/settings/advance/base': RouteRecordInfo<
      '/(auth)/(permission)/settings/advance/base',
      '/settings/advance/base',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(auth)/(permission)/settings/base': RouteRecordInfo<
      '/(auth)/(permission)/settings/base',
      '/settings/base',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(auth)/(permission)/user': RouteRecordInfo<
      '/(auth)/(permission)/user',
      '/user',
      Record<never, never>,
      Record<never, never>,
      | '/(auth)/(permission)/user/'
      | '/(auth)/(permission)/user/advance'
      | '/(auth)/(permission)/user/advance/'
      | '/(auth)/(permission)/user/advance/base'
      | '/(auth)/(permission)/user/base'
    >,
    '/(auth)/(permission)/user/': RouteRecordInfo<
      '/(auth)/(permission)/user/',
      '/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(auth)/(permission)/user/advance': RouteRecordInfo<
      '/(auth)/(permission)/user/advance',
      '/user/advance',
      Record<never, never>,
      Record<never, never>,
      | '/(auth)/(permission)/user/advance/'
      | '/(auth)/(permission)/user/advance/base'
    >,
    '/(auth)/(permission)/user/advance/': RouteRecordInfo<
      '/(auth)/(permission)/user/advance/',
      '/user/advance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(auth)/(permission)/user/advance/base': RouteRecordInfo<
      '/(auth)/(permission)/user/advance/base',
      '/user/advance/base',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(auth)/(permission)/user/base': RouteRecordInfo<
      '/(auth)/(permission)/user/base',
      '/user/base',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(auth)/contact': RouteRecordInfo<
      '/(auth)/contact',
      '/contact',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...slug]': RouteRecordInfo<
      '/[...slug]',
      '/:slug(.*)',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/forbidden': RouteRecordInfo<
      '/forbidden',
      '/forbidden',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(auth)/(permission)/(admin)/(finance)/finance.vue': {
      routes:
        | '/(auth)/(permission)/(admin)/(finance)/finance'
      views:
        | never
    }
    'src/pages/(auth)/(permission)/(admin)/(hr_technical)/hr-technical.vue': {
      routes:
        | '/(auth)/(permission)/(admin)/(hr_technical)/hr-technical'
      views:
        | never
    }
    'src/pages/(auth)/(permission)/(admin)/(hr)/hr.vue': {
      routes:
        | '/(auth)/(permission)/(admin)/(hr)/hr'
      views:
        | never
    }
    'src/pages/(auth)/(permission)/(admin)/(technical)/technical.vue': {
      routes:
        | '/(auth)/(permission)/(admin)/(technical)/technical'
      views:
        | never
    }
    'src/pages/(auth)/(permission)/(admin)/admin.vue': {
      routes:
        | '/(auth)/(permission)/(admin)/admin'
      views:
        | never
    }
    'src/pages/(auth)/(permission)/settings.vue': {
      routes:
        | '/(auth)/(permission)/settings'
        | '/(auth)/(permission)/settings/'
        | '/(auth)/(permission)/settings/advance'
        | '/(auth)/(permission)/settings/advance/'
        | '/(auth)/(permission)/settings/advance/base'
        | '/(auth)/(permission)/settings/base'
      views:
        | 'default'
    }
    'src/pages/(auth)/(permission)/settings/index.vue': {
      routes:
        | '/(auth)/(permission)/settings/'
      views:
        | never
    }
    'src/pages/(auth)/(permission)/settings/advance.vue': {
      routes:
        | '/(auth)/(permission)/settings/advance'
        | '/(auth)/(permission)/settings/advance/'
        | '/(auth)/(permission)/settings/advance/base'
      views:
        | 'default'
    }
    'src/pages/(auth)/(permission)/settings/advance/index.vue': {
      routes:
        | '/(auth)/(permission)/settings/advance/'
      views:
        | never
    }
    'src/pages/(auth)/(permission)/settings/advance/base.vue': {
      routes:
        | '/(auth)/(permission)/settings/advance/base'
      views:
        | never
    }
    'src/pages/(auth)/(permission)/settings/base.vue': {
      routes:
        | '/(auth)/(permission)/settings/base'
      views:
        | never
    }
    'src/pages/(auth)/(permission)/user.vue': {
      routes:
        | '/(auth)/(permission)/user'
        | '/(auth)/(permission)/user/'
        | '/(auth)/(permission)/user/advance'
        | '/(auth)/(permission)/user/advance/'
        | '/(auth)/(permission)/user/advance/base'
        | '/(auth)/(permission)/user/base'
      views:
        | 'default'
    }
    'src/pages/(auth)/(permission)/user/index.vue': {
      routes:
        | '/(auth)/(permission)/user/'
      views:
        | never
    }
    'src/pages/(auth)/(permission)/user/advance.vue': {
      routes:
        | '/(auth)/(permission)/user/advance'
        | '/(auth)/(permission)/user/advance/'
        | '/(auth)/(permission)/user/advance/base'
      views:
        | 'default'
    }
    'src/pages/(auth)/(permission)/user/advance/index.vue': {
      routes:
        | '/(auth)/(permission)/user/advance/'
      views:
        | never
    }
    'src/pages/(auth)/(permission)/user/advance/base.vue': {
      routes:
        | '/(auth)/(permission)/user/advance/base'
      views:
        | never
    }
    'src/pages/(auth)/(permission)/user/base.vue': {
      routes:
        | '/(auth)/(permission)/user/base'
      views:
        | never
    }
    'src/pages/(auth)/contact.vue': {
      routes:
        | '/(auth)/contact'
      views:
        | never
    }
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...slug].vue': {
      routes:
        | '/[...slug]'
      views:
        | never
    }
    'src/pages/about.vue': {
      routes:
        | '/about'
      views:
        | never
    }
    'src/pages/forbidden.vue': {
      routes:
        | '/forbidden'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
